src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $illustration = null;

    #[ORM\Column]
    private ?float $price = null;

    #[ORM\Column]
    private ?float $tva = null;

    #[ORM\ManyToOne(inversedBy: 'products')]
    private ?Category $category = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getIllustration(): ?string
    {
        return $this->illustration;
    }

    public function setIllustration(string $illustration): static
    {
        $this->illustration = $illustration;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getPriceWt() {
        $coeff = 1 + ($this->tva/100);

        return $coeff * $this->price;
    }

    public function getTva(): ?float
    {
        return $this->tva;
    }

    public function setTva(float $tva): static
    {
        $this->tva = $tva;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): static
    {
        $this->category = $category;

        return $this;
    }
}

src/Controller/CartController.php
<?php

namespace App\Controller;

use App\Classe\Cart;
use App\Repository\ProductRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class CartController extends AbstractController
{
    #[Route('/mon-panier', name: 'app_cart')]
    public function index(Cart $cart): Response
    {
        return $this->render('cart/index.html.twig', [
            'cart' => $cart->getCart(),
            'totalPriceWt' => $cart->totalPriceWt(),
        ]);
    }

    #[Route('/cart/add/{id}', name: 'app_cart_add')]
    public function add($id, Cart $cart, ProductRepository $productRepository, Request $request): Response
    {
        $product = $productRepository->findOneById($id);
        $cart->add($product);

        // Creation message de validation : 
        $this->addFlash('success', 'Produit ajouté à votre panier');
        return $this->redirect($request->headers->get('referer'));
    }

    #[Route('/cart/decrease/{id}', name: 'app_cart_decrease')]
    public function decrease($id, Cart $cart): Response
    {

        $cart->decrease($id);

        // Creation message de validation : 
        $this->addFlash('danger', 'Produit retiré à votre panier');
        return $this->redirectToRoute('app_cart');
    }

    #[Route('/cart/remove', name: 'app_cart_remove')]
    public function remove(Cart $cart): Response
    {

        $cart->remove();

        return $this->redirectToRoute('app_home');
    }
}

templates/cart/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	<div class="container my-5">
		<h1>Mon panier</h1>
		<div class='row'>
			<div class='col-md-8'>
				<h2>liste de mes produits</h2>
				{% for product in cart %}
					<div class="row bg-raduis-ligth-blue custom-border m-3 p-4">
						<div class="col-md-2">
							<img src="/uploads/{{ product.product.illustration }}" alt="{{ product.product.name }}" class="img-fluid rounded-3" style="width: 65px;">
						</div>
						<div class="col-md-4">
							<h5>{{ product.product.name }}</h5>
							<p class="small mb-0">{{ product.product.priceWt|price }}</p>
						</div>
						<div class="col-md-3">
							<h5 class="mb-0">
								<a class="link-no-decoration" href="{{ path('app_cart_decrease', {'id': product.product.id}) }}">-
								</a>
								{{ product.qty }}<a class="link-no-decoration" href="{{ path('app_cart_add', {'id': product.product.id}) }}">
									+</a>
							</h5>
						</div>
						<div class="col-md-3">
							<h5 class="mb-0">{{ (product.product.priceWt * product.qty) |price }}</h5>
						</div>
					</div>
				{% endfor %}
				<a class="m-3" href="{{ path('app_cart_remove') }}">Vider votre panier</a>
			</div>
			<div class='col-md-4'>
				<h2>récap de mon panier</h2>
				<div class=" bg-raduis-ligth-blue custom-border m-3 p-4">
					<div class="col-md-4">
						<h5>Total produits :</h5>
						<p class="small mb-0">{{fullCartQuantity}}</p>
						<hr class="hr"/>
						<h5>Prix total :</h5>
						<p class="small mb-0">{{totalPriceWt|price}}</p>
					</div>
				</div>
				<a href="{{ path('app_order') }}" class="m-3 btn btn-primary shadow-0 w-100">
					<i class="bi bi-bag-fill"></i>
					Commander</a>
			</div>
		</div>
	</div>
</div>{% endblock %}